name: radio_app
description: FunAsia Radio Streamer
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  path_provider: ^2.1.1

flutter:
  uses-material-design: true
